### PR TITLE
adding card header search, update badge, form, backgroun, card styles…

### PR DESCRIPTION
**Pull request by masmalsah**
…, update build process

### CODE REVIEW

**Comment by masmalsah** [comment]
@alexphelps  - had to update things to get it working on my local again. Made some changes to achieve the card header search. Let me know if its working for you and maybe run through the update css process tomorrow

**Comment by alexphelps** [comment]
@masmalsah We need to fix card table alignment for the first column. We should also setup example pagination on Cards with tables to show the most common setup of a table/card combo with pagination. 

image

**Comment by alexphelps** [comment]
@masmalsah The example card search header doesn't have an icon like we typically do. Currently we don't support any icons so raises the question on the priority of adding support for and icon library.

We currently use [Feather icons](https://feathericons.com/), they're decent but also very limited selection and don't seem to be getting updates. Potential alternatives:

* [Tabler Icons](https://tabler.io/icons)
* [Bootstrap Icons](https://icons.getbootstrap.com/)

**Comment by masmalsah** [comment]
@alexphelps - added the tabler css from cdn.

**Pull request merged**
